In [ ]:
import torch
print(torch.__version__)

2.10.0+cu128


In [ ]:
if torch.cuda.is_available():
    print("cuda is available")
    print(f"Using GPU :{torch.cuda.get_device_name(0)}")
else:
    print("cuda is not available")

cuda is available
Using GPU :Tesla T4


# **Creating Tensor**

In [ ]:
#using empty
x=torch.empty(4,4)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.7045e-43, 0.0000e+00]])


In [ ]:
#check data type of tensor
type(x)

torch.Tensor

In [ ]:
#initiate a tensor with zero
a=torch.zeros(3,3)
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
#initiate a tensor with 1
ones=torch.ones(2,2)
print(ones)

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
#initiate a tensor with random value
random=torch.rand(2,3)
print(random)

tensor([[0.7323, 0.4268, 0.7525],
        [0.3266, 0.1712, 0.1206]])


In [ ]:
#manual seed ensures that everytime a seed value same sequence of random no are generated
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#despite using random , since its seeded it will now show this same tensor unless a different value of seed is chosen
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#creating tensor with your desirable values
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#a_range method
torch.arange(0,10,2)
#(lower_bound,uppper_bound,step)

tensor([0, 2, 4, 6, 8])

In [ ]:
#using linspace
torch.linspace(0,1,10)

tensor([0.0000, 0.1111, 0.2222, 0.3333, 0.4444, 0.5556, 0.6667, 0.7778, 0.8889,
        1.0000])

In [ ]:
#using eye where a identity matrix is created of desirable dimension
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [ ]:
#using full- a matrix of desired dimension and  one value chosen only
torch.full((2,5),69)

tensor([[69, 69, 69, 69, 69],
        [69, 69, 69, 69, 69]])

# **Tensor Shapes**

In [ ]:
x=torch.tensor([(1,2,3),(4,5,6)])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
# When you call torch.empty_like(input_tensor), the new tensor will automatically inherit the following from the source:

# Shape: The dimensions (e.g., 3×256×256).

# Data Type (dtype): e.g., float32, int64.

# Device: If the original is on the GPU (cuda), the new one will be too.

# Memory Layout: The "strides" or how the data is stored in memory.
torch.empty_like(x)

tensor([[         0, 1038818784,          0],
        [         0,          1,          6]])

In [ ]:
#creating a tensor of same dimension as x with 0s
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
#creating a tensor of same dimension as x with 1s
torch.ones_like(x)


tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
#THIS WILL FAIL
#torch.rand_like(x)

# The function torch.rand is mathematically defined to generate
# continuous decimal values (floating-point) between 0 and 1.
# If your input x is an integer type (like int64 or LongTensor),
# PyTorch refuses to place those decimals into an integer "container"
# to avoid data loss.

# **Tensor** **Data** **Type**

In [ ]:
#find data types
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)


tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1, 2, 3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# **Mathematical Operations**

Scalar **Operation**

In [ ]:
x=torch.rand(2,2)
x

tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])

**Addition,Subtraction,Multiplication,Division,INT Division,Modulo,Power**

In [ ]:
x=x+2# addition
print(x)
x=x-1# subraction
print(x)
x=x*23# multiplaication
print(x)
x=x/(0.5) # Division
print(x)
x=(x*100)//3# INT Division
print(x)
x=x%2# Modulo
print(x)
x=x**2# Power
print(x)


tensor([[2.2627, 2.0428],
        [2.2080, 2.1180]])
tensor([[1.2627, 1.0428],
        [1.2080, 1.1180]])
tensor([[29.0419, 23.9853],
        [27.7847, 25.7149]])
tensor([[58.0838, 47.9706],
        [55.5693, 51.4297]])
tensor([[1936., 1599.],
        [1852., 1714.]])
tensor([[0., 1.],
        [0., 0.]])
tensor([[0., 1.],
        [0., 0.]])


# Element-Wise **Operation**

In [ ]:
a=torch.rand(3,3)
b=torch.rand(3,3)
print(a,'\n',b)

tensor([[0.1217, 0.7356, 0.7118],
        [0.7876, 0.4183, 0.9014],
        [0.9969, 0.7565, 0.2239]]) 
 tensor([[0.3023, 0.1784, 0.8238],
        [0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [ ]:
x=a+b # addition
print(x)
x=a-b #subtraction
print(x)
# multiply
x=a * b
print(x)
# division
x= a / b
print(x)
# power
x=a ** b
print(x)
# mod
x=a % b
print(x)

tensor([[0.4240, 0.9140, 1.5356],
        [1.3433, 1.3953, 1.3454],
        [1.9447, 1.5010, 0.7131]])
tensor([[-0.1807,  0.5572, -0.1121],
        [ 0.2318, -0.5587,  0.4574],
        [ 0.0490,  0.0120, -0.2653]])
tensor([[0.0368, 0.1312, 0.5864],
        [0.4377, 0.4087, 0.4002],
        [0.9449, 0.5632, 0.1095]])
tensor([[0.4025, 4.1229, 0.8640],
        [1.4172, 0.4281, 2.0301],
        [1.0517, 1.0162, 0.4577]])
tensor([[0.5290, 0.9467, 0.7557],
        [0.8757, 0.4268, 0.9550],
        [0.9970, 0.8124, 0.4809]])
tensor([[0.1217, 0.0219, 0.7118],
        [0.2318, 0.4183, 0.0134],
        [0.0490, 0.0120, 0.2239]])


In [ ]:
c=torch.tensor([1,-2,3,-4,5,-6])

In [ ]:
#Absolute
torch.abs(c)

tensor([1, 2, 3, 4, 5, 6])

In [ ]:
# Negative
torch.neg(c)

tensor([-1,  2, -3,  4, -5,  6])

In [ ]:
d=torch.rand(1,5)*5
d

tensor([[1.2128, 3.5017, 2.6384, 1.2359, 3.9544]])

In [ ]:
# round
torch.round(d)

tensor([[1., 4., 3., 1., 4.]])

In [ ]:
# ceil-Equals to the next greatest  integer value
torch.ceil(d)

tensor([[2., 4., 3., 2., 4.]])

In [ ]:
# floor
torch.floor(d)

tensor([[1., 3., 2., 1., 3.]])

In [ ]:
# clamp-The torch.clamp function restricts all elements in an input tensor to be within a specified range [min, max].
torch.clamp(d, min=2, max=3)

tensor([[2.0000, 3.0000, 2.6384, 2.0000, 3.0000]])

# **Reduction Operation**

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[9., 5., 7.],
        [3., 9., 4.]])

In [ ]:
# sum
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([21., 16.])

In [ ]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([6.0000, 7.0000, 5.5000])

In [ ]:
# median
torch.median(e)

tensor(5.)

In [ ]:
# max and min
torch.max(e)
torch.min(e)

tensor(3.)

In [ ]:
# product
torch.prod(e)

tensor(34020.)

In [ ]:
# standard deviation
torch.std(e)

tensor(2.5626)

In [ ]:
# variance
torch.var(e)

tensor(6.5667)

In [ ]:
# argmax-give the position of the max valued element in the tensor
torch.argmax(e)

tensor(0)

In [ ]:
# argmin-give the position of the min valued element in the tensor
torch.argmin(e)

tensor(3)

# **Matrix** **Operation**

In [ ]:
manual_seed=torch.manual_seed(42)
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,3),low=0,high=10) # Changed g to a 3x3 square matrix
print(f)
print(g)

tensor([[2, 7, 6],
        [4, 6, 5]])
tensor([[0, 4, 0],
        [3, 8, 4],
        [0, 4, 1]])


In [ ]:
torch.matmul(f,g)

tensor([[21, 88, 34],
        [18, 84, 29]])

In [ ]:
v1=torch.rand(3)
v2=torch.rand(3)
print(v1)
print(v2)
torch.dot(v1,v2)

tensor([0.4294, 0.8854, 0.5739])
tensor([0.2666, 0.6274, 0.2696])


tensor(0.8248)

In [ ]:
torch.transpose(f,0,1)

tensor([[2, 4],
        [7, 6],
        [6, 5]])

In [ ]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
print(h)
torch.det(h)

tensor([[6., 3., 1.],
        [9., 3., 1.],
        [9., 7., 9.]])


tensor(-60.)

In [ ]:
torch.inverse(h)

tensor([[-3.3333e-01,  3.3333e-01,  1.8626e-09],
        [ 1.2000e+00, -7.5000e-01, -5.0000e-02],
        [-6.0000e-01,  2.5000e-01,  1.5000e-01]])

# **Comparison Operator**

In [ ]:
i=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
j=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
print(i,'\n',j)

tensor([[2., 0., 5.],
        [9., 3., 4.]]) 
 tensor([[9., 6., 2.],
        [0., 6., 2.]])


In [ ]:
# greater than
i > j


tensor([[False, False,  True],
        [ True, False,  True]])

In [ ]:
# less than
i < j


tensor([[ True,  True, False],
        [False,  True, False]])

In [ ]:
# equal to
i == j


tensor([[False, False, False],
        [False, False, False]])

In [ ]:
# not equal to
i != j


tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[7., 9., 7.],
        [3., 3., 4.]])

In [ ]:
# log
torch.log(k)

tensor([[1.9459, 2.1972, 1.9459],
        [1.0986, 1.0986, 1.3863]])

In [ ]:
# exp
torch.exp(k)

tensor([[1096.6332, 8103.0840, 1096.6332],
        [  20.0855,   20.0855,   54.5981]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[2.6458, 3.0000, 2.6458],
        [1.7321, 1.7321, 2.0000]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9991, 0.9999, 0.9991],
        [0.9526, 0.9526, 0.9820]])

In [ ]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.9820, 0.9975, 0.9526],
        [0.0180, 0.0025, 0.0474]])

In [ ]:
# relu
torch.relu(k)

tensor([[7., 9., 7.],
        [3., 3., 4.]])

### 6. Special functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[3., 7., 0.],
        [9., 0., 9.]])

In [ ]:
# log
torch.log(k)

tensor([[1.0986, 1.9459,   -inf],
        [2.1972,   -inf, 2.1972]])

In [ ]:
# exp
torch.exp(k)

tensor([[2.0086e+01, 1.0966e+03, 1.0000e+00],
        [8.1031e+03, 1.0000e+00, 8.1031e+03]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[1.7321, 2.6458, 0.0000],
        [3.0000, 0.0000, 3.0000]])

In [ ]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9526, 0.9991, 0.5000],
        [0.9999, 0.5000, 0.9999]])

In [ ]:
# softmax
torch.softmax(k, dim=0)

tensor([[2.4726e-03, 9.9909e-01, 1.2339e-04],
        [9.9753e-01, 9.1105e-04, 9.9988e-01]])

In [ ]:
# relu
torch.relu(k)

tensor([[3., 7., 0.],
        [9., 0., 9.]])

## Inplace Operations

In [ ]:
manual_seed=torch.manual_seed(69)
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.8398, 0.8042, 0.1213],
        [0.5309, 0.6646, 0.4077]])
tensor([[0.0888, 0.2429, 0.7053],
        [0.6216, 0.9188, 0.0185]])


In [ ]:
m=m+n#here a new memory is allocated for addition then put back in 'm'
m

tensor([[0.9286, 1.0470, 0.8267],
        [1.1526, 1.5834, 0.4262]])

In [ ]:
m.add_(n)#This doesnt create a new location at all


tensor([[1.0173, 1.2899, 1.5320],
        [1.7742, 2.5022, 0.4448]])

In [ ]:
torch.relu(m)

tensor([[1.0173, 1.2899, 1.5320],
        [1.7742, 2.5022, 0.4448]])

In [ ]:
m.relu_()

tensor([[1.0173, 1.2899, 1.5320],
        [1.7742, 2.5022, 0.4448]])

## Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.8741, 0.0560, 0.9659],
        [0.0073, 0.3628, 0.4197]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.8741, 0.0560, 0.9659],
        [0.0073, 0.3628, 0.4197]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.0560, 0.9659],
        [0.0073, 0.3628, 0.4197]])

In [ ]:
b

tensor([[0.0000, 0.0560, 0.9659],
        [0.0073, 0.3628, 0.4197]])

In [ ]:
id(a)

135269076447504

In [ ]:
id(b)

135269076447504

In [ ]:
b = a.clone()

In [ ]:
a

tensor([[0.0000, 0.0560, 0.9659],
        [0.0073, 0.3628, 0.4197]])

In [ ]:
b

tensor([[0.0000, 0.0560, 0.9659],
        [0.0073, 0.3628, 0.4197]])

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[1.0000e+01, 5.5990e-02, 9.6595e-01],
        [7.2868e-03, 3.6285e-01, 4.1968e-01]])

In [ ]:
b

tensor([[0.0000, 0.0560, 0.9659],
        [0.0073, 0.3628, 0.4197]])

In [ ]:
id(a)

135269076447504

In [ ]:
id(b)

135269063315040

In [ ]:
m

tensor([[1.0173, 1.2899, 1.5320],
        [1.7742, 2.5022, 0.4448]])

# Tensor Operation on **GPU**

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')

<h3 style="color:#2a7ae2;">🚀 PyTorch Device Setup </h3>

-   **`torch.cuda.is_available()`**:
    -   Checks for the presence and accessibility of a CUDA-enabled GPU.
    -   Returns `True` if a compatible NVIDIA GPU and drivers/CUDA toolkit are installed.

-   **`'cuda' if torch.cuda.is_available() else 'cpu'`**:
    -   A Python conditional expression.
    -   Evaluates to the string `'cuda'` if a GPU is available.
    -   Evaluates to the string `'cpu'` if no GPU is available.

-   **`torch.device(...)`**:
    -   Constructs a `torch.device` object based on the conditional expression.
    -   This `device` variable then specifies where PyTorch tensors and models should reside (GPU or CPU).

This setup allows your code to:
-   Leverage GPU acceleration when available for significant speedups.
-   Automatically fall back to CPU when a GPU is not found, ensuring portability.

In [ ]:
#Creating a new tensor on GPU

torch.rand((2,3),device=device)

tensor([[0.2492, 0.1466, 0.6058],
        [0.5550, 0.3204, 0.5613]], device='cuda:0')

In [ ]:
# Moving an Existing Tensor to GPU
a=torch.rand((2,3))# created on CPU
b=a.to(device) # Moved to Gpu on a different name
print(a,'\n',b)

tensor([[0.6444, 0.0099, 0.5925],
        [0.9631, 0.6958, 0.9157]]) 
 tensor([[0.6444, 0.0099, 0.5925],
        [0.9631, 0.6958, 0.9157]], device='cuda:0')


In [ ]:
import time

# Define the size of the matrices
size = 10000 # Large size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)# Matrix Mul on CPU
cpu_time = time.time() - start_time
print(f"Time on CPU: {cpu_time:.4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2) # Matrix multiplication on GPU
torch.cuda.synchronize() # Ensure all GPU operations are complete
gpu_time = time.time() - start_time
print(f"Time on GPU: {gpu_time:.4f} seconds")

#Compare the Result
print("\nSpeedup:", cpu_time / gpu_time)

Time on CPU: 19.8759 seconds
Time on GPU: 0.7034 seconds

Speedup: 28.25548125351645


# **Reshaping Tensors**

In [ ]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#Reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
b=torch.rand(2,3,4)
b

tensor([[[0.8994, 0.1933, 0.9665, 0.1012],
         [0.9408, 0.3695, 0.9277, 0.5383],
         [0.1673, 0.4889, 0.4550, 0.1625]],

        [[0.3745, 0.5378, 0.9062, 0.6305],
         [0.9152, 0.1323, 0.4032, 0.8436],
         [0.0124, 0.1375, 0.7342, 0.9974]]])

### 🔄 Tensor Manipulation: `Permute`, `Squeeze`, and `Unsqueeze`

These functions are essential for changing the shape and arrangement of tensors without altering their underlying data. They are crucial for preparing data for models, matching expected input shapes, and handling batch dimensions.

---

#### 1. `torch.permute()`

*   **What it does:** Rearranges the dimensions (axes) of a tensor according to a specified order. It's like transposing a 2D matrix, but for any number of dimensions.
*   **How it works:** You provide a tuple or list of integers representing the new order of dimensions. For example, if a tensor has shape `(D0, D1, D2)`, `tensor.permute(1, 2, 0)` would change its shape to `(D1, D2, D0)`.
*   **When to use it:**
    *   **Changing Image Data Layout:** Many image processing tasks and models (especially in PyTorch) expect image data in `(Batch, Channels, Height, Width)` format, while common loading libraries might produce `(Batch, Height, Width, Channels)`. `permute` is used to switch `HWC` to `CHW` (e.g., `image.permute(0, 3, 1, 2)`).
    *   **Aligning Dimensions:** When performing operations between tensors that require specific dimension alignment (e.g., matrix multiplication, broadcasting).

---

#### 2. `torch.squeeze()`

*   **What it does:** Removes all dimensions of size 1 from the tensor's shape.
*   **How it works:** If a tensor has a shape like `(1, 3, 1, 256, 1)`, `squeeze()` would result in a shape of `(3, 256)`. You can also specify a `dim` argument to remove a dimension of size 1 at a particular index (e.g., `tensor.squeeze(0)` would remove the first dimension if it's size 1).
*   **When to use it:**
    *   **Removing Redundant Batch Dimensions:** Often, when processing a single item, you might add a batch dimension of size 1 (e.g., `(1, Channels, Height, Width)`). After processing, you might want to remove this singleton dimension to get `(Channels, Height, Width)`.
    *   **Cleaning Up Shapes:** Simplifying tensor shapes after operations that might introduce unnecessary singleton dimensions.

---

#### 3. `torch.unsqueeze()`

*   **What it does:** Adds a dimension of size 1 to the tensor's shape at a specified position.
*   **How it works:** You provide the `dim` argument (an integer) where the new dimension should be inserted. For example, if a tensor has shape `(3, 256)`, `tensor.unsqueeze(0)` would result in `(1, 3, 256)`. `tensor.unsqueeze(1)` would result in `(3, 1, 256)`.
*   **When to use it:**
    *   **Adding Batch Dimensions:** Most neural networks expect inputs to have a batch dimension (even if it's a batch of one). If you have a single image with shape `(Channels, Height, Width)`, you'd use `image.unsqueeze(0)` to make it `(1, Channels, Height, Width)`.
    *   **Broadcasting:** Preparing tensors for broadcasting operations where one tensor needs an extra dimension to match the other's shape.
    *   **Feature Expansion:** Adding a new dimension to represent a single feature map or channel where the model expects an explicit dimension.

In [ ]:
#Permute
b.permute(2,0,1).shape


torch.Size([4, 2, 3])

In [ ]:
#Unsqueeze
c=torch.rand(226,226,3)
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])